freebsd_instance:
  image: freebsd-12-0-release-amd64

task:
  install_script:
    - pkg update
    - pkg install -y python37 py36-psycopg2 py36-ucl rsync git
  script:
    - pkg install -y postgresql11-server yarn
    - sysrc postgresql_enable=YES
    - service postgresql initdb
    - service postgresql start
    - sudo -u postgres createuser jaisting
    - sudo -u postgres psql -c "alter user jaisting with encrypted password 'jaisting'"
    - sudo -u postgres psql -c "alter role jaisting with createdb"
    - python3.7 -m ensurepip
    - python3.7 -m pip install Cython==0.29.5
    - python3.7 -m pip install -r packages.txt
    - yarn install
    - ./node_modules/.bin/webpack --config webpack.config.js --mode=development
    - flake8 ./**/*.py
    - python3.7 manage.py test

