freebsd_instance:
  image: freebsd-12-0-release-amd64

task:
  install_script:
    - pkg update
    - pkg install -y python37 py36-psycopg2 py36-ucl rsync git postgresql11-server postgresql11-client yarn
  script:
    - sysrc postgresql_enable=YES
    - /usr/local/etc/rc.d/postgresql initdb
    - /usr/local/etc/rc.d/postgresql start
    - sudo -u postgres createuser jaisting
    - sudo -u postgres createdb jaisting_test
    - sudo -u postgres psql -c "alter user jaisting with encrypted password 'jaisting'"
    - sudo -u postgres psql -c "grant all privileges on database jaisting_test to jaisting"
    - python3.7 -m ensurepip
    - python3.7 -m pip install Cython==0.29.5
    - python3.7 -m pip install -r packages.txt
    - python3.7 manage.py migrate
    - yarn install
    - ./node_modules/.bin/webpack --config webpack.config.js --mode=development

